In [5]:
import pandas as pd;
import openpyxl;
path = r"H:\python\3etapa\atividade_4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"
indicador_1 = pd.read_excel(path, header = 2)

In [16]:
indicador_1

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
tabela_prime = indicador_1.iloc[0:5570, 1:]

In [15]:
tabela_prime

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,2898.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0,-6480.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0,962.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0,-8313.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0,1139.0
...,...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0,-2408.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,-1397.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0,520.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0,-670.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,-247221.0

In [9]:
tabela_prime.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022'],
      dtype='str')

In [14]:
tabela_prime["diferença"] = tabela_prime['População Município 2010\n(Sinopse)'] - tabela_prime[ 'População Censo 2022']

In [13]:
tabela_prime.to_csv(r"H:\python\3etapa\atividade_4\diferença20222010.csv", sep=";")

In [25]:
tabela_fodastica= (
    tabela_prime.groupby("UF")[['População Município 2010\n(Sinopse)',"População Censo 2022", "diferença" ]]
    .sum()
    .reset_index()
)

In [27]:
tabela_prime.to_csv(r"H:\python\3etapa\atividade_4\diferença20222010estado.csv", sep=";")

    População Município 2010\n(Sinopse)  População Censo 2022  diferença
UF
AC                             733559.0              830018.0   -96459.0
AL                            3120494.0             3127683.0    -7189.0
AM                            3483985.0             3941613.0  -457628.0
AP                             669526.0              733759.0   -64233.0
BA                           14016906.0            14141626.0  -124720.0
CE                            8452381.0             8794957.0  -342576.0
DF                            2570160.0             2817381.0  -247221.0
ES                            3514952.0             3833712.0  -318760.0
GO                            6003788.0             7056495.0 -1052707.0
MA                            6574789.0             6776699.0  -201910.0
MG                           19597330.0            20539989.0  -942659.0
MS                            2449024.0             2757013.0  -307989.0
MT                            3035122.0             3658649.0  -623527.0
PA                            7581051.0             8120131.0  -539080.0
PB                            3766528.0             3974687.0  -208159.0
PE                            8796448.0             9058931.0  -262483.0
PI                            3118360.0             3271199.0  -152839.0
PR                           10444526.0            11444380.0  -999854.0
RJ                           15989929.0            16055174.0   -65245.0
RN                            3168027.0             3302729.0  -134702.0
RO                            1562409.0             1581196.0   -18787.0
RR                             450479.0              636707.0  -186228.0
RS                           10693929.0            10882965.0  -189036.0
SC                            6248436.0             7610361.0 -1361925.0
SE                            2068017.0             2210004.0  -141987.0
SP                           41262199.0            44411238.0 -3149039.0
TO                            1383445.0             1511460.0  -128015.0